#+TITLE: Thesis
#+AUTHOR: Chris Liourtas

* IoT data visualization methods for autonomous devices using MQTT
This is the repositoty where I keep all of my relevant notes,code and references for my thesis. The whole
project is managed using emacs and org-mode.

* Directories
** Notes
The notes directory contains copies of my org-roam notes related to this thesis.
** Rust
Implementations of relevant code in rust.
** Wiring
Implementations of relevant code in C++ with the Arduino framework using PlatformIO.
** [[file:agenda/agenda.org][Agenda]]
Collection of references with relevant timestamps and org states (TODOs, etc).
** Write
Segments of the thesis that are meant to be into the final paper.
* Build & Run
So far I have been using PlatformIO on a python virtual enviroment.
For example to run esp32-wifi on terminal.
#+begin_src bash
  cd wiring/esp32-wifi/
  source ./wiring/esp32/esp32_pio_venv/bin/activate
  pio run
#+end_src
* Add new code
** PlatformIO
#+begin_src bash
  python -m venv ./platformio_venv_example/
  source ./platformio_venv_example/bin/activate
  pip install platformio
  pio project init
#+end_src
Example build configuration for esp32 with ThingsBoard library and its dependencies:
#+begin_src toml
[env:esp32dev]
platform = espressif32
board = esp32dev
board_build.mcu = esp32
board_build.f_cpu = 240000000L
framework = arduino
targets = upload, monitor
monitor_speed = 115200
lib_deps = Update
           thingsboard/ThingsBoard@0.11.0
	   bblanchon/ArduinoJson
	   thingsboard/TBPubSubClient
	   arduino-libraries/ArduinoHttpClient
	   bblanchon/StreamUtils
#+end_src
