services:
  thingsboard:
    image: "thingsboard/tb-postgres"
    container_name: thingsboard
    ports:
      - 8080:9090
      - 1999:1883
      - 7070:7070
      - 5683-5688:5683-5688/udp
    environment:
       TB_QUEUE_TYPE: in-memory
    volumes:
      - ./thingsboard/data:/thingsboard/data/
      - ./thingsboard/logs:/thingsboard/logs/
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/config/pwfile:/mosquitto/config/pwfile
      - ./mosquitto/data/:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
